// Generated by CoffeeScript 1.8.0
(function() {
  describe('PhoneCat controllers', function() {
    return describe('PhoneListCtrl', function() {
      var $httpBackend, ctrl, scope;
      scope = null;
      ctrl = null;
      $httpBackend = null;
      beforeEach(module('phonecatApp'));
      beforeEach(inject(function(_$httpBackend_, $rootScope, $controller) {
        $httpBackend = _$httpBackend_;
        $httpBackend.expectGET('phones/phones.json').respond([
          {
            name: 'Nexus S'
          }, {
            name: 'Motorola DROID'
          }
        ]);
        scope = $rootScope.$new();
        return ctrl = $controller('PhoneListCtrl', {
          $scope: scope
        });
      }));
      return it('should create "phones" model with 2 phones fetched from xhr', function() {
        expect(scope.phones).toBeUndefined();
        $httpBackend.flush;
        return expect(scope.phones).toEqual([
          {
            name: 'Nexus S'
          }, {
            name: 'Motorola DROID'
          }
        ]);
      });
    });
  });

}).call(this);

//# sourceMappingURL=controllersSpec.js.map
