// Generated by CoffeeScript 1.8.0
(function() {
  describe('PhoneCat controllers', function() {
    return describe('PhoneListCtrl', function() {
      var ctrl, scope;
      scope = null;
      ctrl = null;
      beforeEach(module('phonecatApp'));
      beforeEach(inject(function($controller) {
        scope = {};
        return ctrl = $controller('PhoneListCtrl', {
          $scope: scope
        });
      }));
      it('should create "phones" model with 3 phones', function() {
        return expect(scope.phones.length).toBe(3);
      });
      return it('should set the default value of orderProp model', function() {
        return expect(scope.orderProp).toBe('age');
      });
    });
  });

}).call(this);

//# sourceMappingURL=controllersSpec.js.map
